deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - ssh atnog@10.0.12.91 "cd ~/git/static-objects; git pull; sudo systemctl reload nginx; sudo docker restart backend-emulator;"
